import pandas as pd
import numpy as np

import re
imagenet = ["tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark", "electric ray", "stingray", "cock", "hen", "ostrich", "brambling", "goldfinch", "house finch", "junco", "indigo bunting", "American robin", "bulbul", "jay", "magpie", "chickadee", "American dipper", "kite", "bald eagle", "vulture", "great grey owl", "fire salamander", "smooth newt", "newt", "spotted salamander", "axolotl", "American bullfrog", "tree frog", "tailed frog", "loggerhead sea turtle", "leatherback sea turtle", "mud turtle", "terrapin", "box turtle", "banded gecko", "green iguana", "Carolina anole", "desert grassland whiptail lizard", "agama", "frilled-necked lizard", "alligator lizard", "Gila monster", "European green lizard", "chameleon", "Komodo dragon", "Nile crocodile", "American alligator", "triceratops", "worm snake", "ring-necked snake", "eastern hog-nosed snake", "smooth green snake", "kingsnake", "garter snake", "water snake", "vine snake", "night snake", "boa constrictor", "African rock python", "Indian cobra", "green mamba", "sea snake", "Saharan horned viper", "eastern diamondback rattlesnake", "sidewinder", "trilobite", "harvestman", "scorpion", "yellow garden spider", "barn spider", "European garden spider", "southern black widow", "tarantula", "wolf spider", "tick", "centipede", "black grouse", "ptarmigan", "ruffed grouse", "prairie grouse", "peacock", "quail", "partridge", "grey parrot", "macaw", "sulphur-crested cockatoo", "lorikeet", "coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "duck", "red-breasted merganser", "goose", "black swan", "tusker", "echidna", "platypus", "wallaby", "koala", "wombat", "jellyfish", "sea anemone", "brain coral", "flatworm", "nematode", "conch", "snail", "slug", "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab", "fiddler crab", "red king crab", "American lobster", "spiny lobster", "crayfish", "hermit crab", "isopod", "white stork", "black stork", "spoonbill", "flamingo", "little blue heron", "great egret", "bittern", "crane (bird)", "limpkin", "common gallinule", "American coot", "bustard", "ruddy turnstone", "dunlin", "common redshank", "dowitcher", "oystercatcher", "pelican", "king penguin", "albatross", "grey whale", "killer whale", "dugong", "sea lion", "Chihuahua", "Japanese Chin", "Maltese", "Pekingese", "Shih Tzu", "King Charles Spaniel", "Papillon", "toy terrier", "Rhodesian Ridgeback", "Afghan Hound", "Basset Hound", "Beagle", "Bloodhound", "Bluetick Coonhound", "Black and Tan Coonhound", "Treeing Walker Coonhound", "English foxhound", "Redbone Coonhound", "borzoi", "Irish Wolfhound", "Italian Greyhound", "Whippet", "Ibizan Hound", "Norwegian Elkhound", "Otterhound", "Saluki", "Scottish Deerhound", "Weimaraner", "Staffordshire Bull Terrier", "American Staffordshire Terrier", "Bedlington Terrier", "Border Terrier", "Kerry Blue Terrier", "Irish Terrier", "Norfolk Terrier", "Norwich Terrier", "Yorkshire Terrier", "Wire Fox Terrier", "Lakeland Terrier", "Sealyham Terrier", "Airedale Terrier", "Cairn Terrier", "Australian Terrier", "Dandie Dinmont Terrier", "Boston Terrier", "Miniature Schnauzer", "Giant Schnauzer", "Standard Schnauzer", "Scottish Terrier", "Tibetan Terrier", "Australian Silky Terrier", "Soft-coated Wheaten Terrier", "West Highland White Terrier", "Lhasa Apso", "Flat-Coated Retriever", "Curly-coated Retriever", "Golden Retriever", "Labrador Retriever", "Chesapeake Bay Retriever", "German Shorthaired Pointer", "Vizsla", "English Setter", "Irish Setter", "Gordon Setter", "Brittany", "Clumber Spaniel", "English Springer Spaniel", "Welsh Springer Spaniel", "Cocker Spaniels", "Sussex Spaniel", "Irish Water Spaniel", "Kuvasz", "Schipperke", "Groenendael", "Malinois", "Briard", "Australian Kelpie", "Komondor", "Old English Sheepdog", "Shetland Sheepdog", "collie", "Border Collie", "Bouvier des Flandres", "Rottweiler", "German Shepherd Dog", "Dobermann", "Miniature Pinscher", "Greater Swiss Mountain Dog", "Bernese Mountain Dog", "Appenzeller Sennenhund", "Entlebucher Sennenhund", "Boxer", "Bullmastiff", "Tibetan Mastiff", "French Bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute", "Siberian Husky", "Dalmatian", "Affenpinscher", "Basenji", "pug", "Leonberger", "Newfoundland", "Pyrenean Mountain Dog", "Samoyed", "Pomeranian", "Chow Chow", "Keeshond", "Griffon Bruxellois", "Pembroke Welsh Corgi", "Cardigan Welsh Corgi", "Toy Poodle", "Miniature Poodle", "Standard Poodle", "Mexican hairless dog", "grey wolf", "Alaskan tundra wolf", "red wolf", "coyote", "dingo", "dhole", "African wild dog", "hyena", "red fox", "kit fox", "Arctic fox", "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat", "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard", "jaguar", "lion", "tiger", "cheetah", "brown bear", "American black bear", "polar bear", "sloth bear", "mongoose", "meerkat", "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle", "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "ant", "grasshopper", "cricket", "stick insect", "cockroach", "mantis", "cicada", "leafhopper", "lacewing", "dragonfly", "damselfly", "red admiral", "ringlet", "monarch butterfly", "small white", "sulphur butterfly", "gossamer-winged butterfly", "starfish", "sea urchin", "sea cucumber", "cottontail rabbit", "hare", "Angora rabbit", "hamster", "porcupine", "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel", "zebra", "pig", "wild boar", "warthog", "hippopotamus", "ox", "water buffalo", "bison", "ram", "bighorn sheep", "Alpine ibex", "hartebeest", "impala", "gazelle", "dromedary", "llama", "weasel", "mink", "European polecat", "black-footed ferret", "otter", "skunk", "badger", "armadillo", "three-toed sloth", "orangutan", "gorilla", "chimpanzee", "gibbon", "siamang", "guenon", "patas monkey", "baboon", "macaque", "langur", "black-and-white colobus", "proboscis monkey", "marmoset", "white-headed capuchin", "howler monkey", "titi", "Geoffroy's spider monkey", "common squirrel monkey", "ring-tailed lemur", "indri", "Asian elephant", "African bush elephant", "red panda", "giant panda", "snoek", "eel", "coho salmon", "rock beauty", "clownfish", "sturgeon", "garfish", "lionfish", "pufferfish", "abacus", "abaya", "academic gown", "accordion", "acoustic guitar", "aircraft carrier", "airliner", "airship", "altar", "ambulance", "amphibious vehicle", "analog clock", "apiary", "apron", "waste container", "assault rifle", "backpack", "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid", "banjo", "baluster", "barbell", "barber chair", "barbershop", "barn", "barometer", "barrel", "wheelbarrow", "baseball", "basketball", "bassinet", "bassoon", "swimming cap", "bath towel", "bathtub", "station wagon", "lighthouse", "beaker", "military cap", "beer bottle", "beer glass", "bell-cot", "bib", "tandem bicycle", "bikini", "ring binder", "binoculars", "birdhouse", "boathouse", "bobsleigh", "bolo tie", "poke bonnet", "bookcase", "bookstore", "bottle cap", "bow", "bow tie", "brass", "bra", "breakwater", "breastplate", "broom", "bucket", "buckle", "bulletproof vest", "high-speed train", "butcher shop", "taxicab", "cauldron", "candle", "cannon", "canoe", "can opener", "cardigan", "car mirror", "carousel", "tool kit", "carton", "car wheel", "automated teller machine", "cassette", "cassette player", "castle", "catamaran", "CD player", "cello", "mobile phone", "chain", "chain-link fence", "chain mail", "chainsaw", "chest", "chiffonier", "chime", "china cabinet", "Christmas stocking", "church", "movie theater", "cleaver", "cliff dwelling", "cloak", "clogs", "cocktail shaker", "coffee mug", "coffeemaker", "coil", "combination lock", "computer keyboard", "confectionery store", "container ship", "convertible", "corkscrew", "cornet", "cowboy boot", "cowboy hat", "cradle", "crane (machine)", "crash helmet", "crate", "infant bed", "Crock Pot", "croquet ball", "crutch", "cuirass", "dam", "desk", "desktop computer", "rotary dial telephone", "diaper", "digital clock", "digital watch", "dining table", "dishcloth", "dishwasher", "disc brake", "dock", "dog sled", "dome", "doormat", "drilling rig", "drum", "drumstick", "dumbbell", "Dutch oven", "electric fan", "electric guitar", "electric locomotive", "entertainment center", "envelope", "espresso machine", "face powder", "feather boa", "filing cabinet", "fireboat", "fire engine", "fire screen sheet", "flagpole", "flute", "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed", "freight car", "French horn", "frying pan", "fur coat", "garbage truck", "gas mask", "gas pump", "goblet", "go-kart", "golf ball", "golf cart", "gondola", "gong", "gown", "grand piano", "greenhouse", "grille", "grocery store", "guillotine", "barrette", "hair spray", "half-track", "hammer", "hamper", "hair dryer", "hand-held computer", "handkerchief", "hard disk drive", "harmonica", "harp", "harvester", "hatchet", "holster", "home theater", "honeycomb", "hook", "hoop skirt", "horizontal bar", "horse-drawn vehicle", "hourglass", "iPod", "clothes iron", "jack-o'-lantern", "jeans", "jeep", "T-shirt", "jigsaw puzzle", "pulled rickshaw", "joystick", "kimono", "knee pad", "knot", "lab coat", "ladle", "lampshade", "laptop computer", "lawn mower", "lens cap", "paper knife", "library", "lifeboat", "lighter", "limousine", "ocean liner", "lipstick", "slip-on shoe", "lotion", "speaker", "loupe", "sawmill", "magnetic compass", "mail bag", "mailbox", "tights", "tank suit", "manhole cover", "maraca", "marimba", "mask", "match", "maypole", "maze", "measuring cup", "medicine chest", "megalith", "microphone", "microwave oven", "military uniform", "milk can", "minibus", "miniskirt", "minivan", "missile", "mitten", "mixing bowl", "mobile home", "Model T", "modem", "monastery", "monitor", "moped", "mortar", "square academic cap", "mosque", "mosquito net", "scooter", "mountain bike", "tent", "computer mouse", "mousetrap", "moving van", "muzzle", "nail", "neck brace", "necklace", "nipple", "notebook computer", "obelisk", "oboe", "ocarina", "odometer", "oil filter", "organ", "oscilloscope", "overskirt", "bullock cart", "oxygen mask", "packet", "paddle", "paddle wheel", "padlock", "paintbrush", "pajamas", "palace", "pan flute", "paper towel", "parachute", "parallel bars", "park bench", "parking meter", "passenger car", "patio", "payphone", "pedestal", "pencil case", "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum", "Pickelhaube", "picket fence", "pickup truck", "pier", "piggy bank", "pill bottle", "pillow", "ping-pong ball", "pinwheel", "pirate ship", "pitcher", "hand plane", "planetarium", "plastic bag", "plate rack", "plow", "plunger", "Polaroid camera", "pole", "police van", "poncho", "billiard table", "soda bottle", "pot", "potter's wheel", "power drill", "prayer rug", "printer", "prison", "projectile", "projector", "hockey puck", "punching bag", "purse", "quill", "quilt", "race car", "racket", "radiator", "radio", "radio telescope", "rain barrel", "recreational vehicle", "reel", "reflex camera", "refrigerator", "remote control", "restaurant", "revolver", "rifle", "rocking chair", "rotisserie", "eraser", "rugby ball", "ruler", "running shoe", "safe", "safety pin", "salt shaker", "sandal", "sarong", "saxophone", "scabbard", "weighing scale", "school bus", "schooner", "scoreboard", "CRT screen", "screw", "screwdriver", "seat belt", "sewing machine", "shield", "shoe store", "shoji", "shopping basket", "shopping cart", "shovel", "shower cap", "shower curtain", "ski", "ski mask", "sleeping bag", "slide rule", "sliding door", "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser", "soccer ball", "sock", "solar thermal collector", "sombrero", "soup bowl", "space bar", "space heater", "space shuttle", "spatula", "motorboat", "spider web", "spindle", "sports car", "spotlight", "stage", "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf", "stone wall", "stopwatch", "stove", "strainer", "tram", "stretcher", "couch", "stupa", "submarine", "suit", "sundial", "sunglass", "sunglasses", "sunscreen", "suspension bridge", "mop", "sweatshirt", "swimsuit", "swing", "switch", "syringe", "table lamp", "tank", "tape player", "teapot", "teddy bear", "television", "tennis ball", "thatched roof", "front curtain", "thimble", "threshing machine", "throne", "tile roof", "toaster", "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck", "toy store", "tractor", "semi-trailer truck", "tray", "trench coat", "tricycle", "trimaran", "tripod", "triumphal arch", "trolleybus", "trombone", "tub", "turnstile", "typewriter keyboard", "umbrella", "unicycle", "upright piano", "vacuum cleaner", "vase", "vault", "velvet", "vending machine", "vestment", "viaduct", "violin", "volleyball", "waffle iron", "wall clock", "wallet", "wardrobe", "military aircraft", "sink", "washing machine", "water bottle", "water jug", "water tower", "whiskey jug", "whistle", "wig", "window screen", "window shade", "Windsor tie", "wine bottle", "wing", "wok", "wooden spoon", "wool", "split-rail fence", "shipwreck", "yawl", "yurt", "website", "comic book", "crossword", "traffic sign", "traffic light", "dust jacket", "menu", "plate", "guacamole", "consomme", "hot pot", "trifle", "ice cream", "ice pop", "baguette", "bagel", "pretzel", "cheeseburger", "hot dog", "mashed potato", "cabbage", "broccoli", "cauliflower", "zucchini", "spaghetti squash", "acorn squash", "butternut squash", "cucumber", "artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith", "strawberry", "orange", "lemon", "fig", "pineapple", "banana", "jackfruit", "custard apple", "pomegranate", "hay", "carbonara", "chocolate syrup", "dough", "meatloaf", "pizza", "pot pie", "burrito", "red wine", "espresso", "cup", "eggnog", "alp", "bubble", "cliff", "coral reef", "geyser", "lakeshore", "promontory", "shoal", "seashore", "valley", "volcano", "baseball player", "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper", "corn", "acorn", "rose hip", "horse chestnut seed", "coral fungus", "agaric", "gyromitra", "stinkhorn mushroom", "earth star", "hen-of-the-woods", "bolete", "ear", "toilet paper"]

def dictionary_replace(new_key, old_key):
    topology_dict[new_key] = topology_dict[old_key]
    del topology_dict[old_key]

df = pd.read_csv("imagenet_categories.csv")
file1 = open('imagenet1000_clsidx_to_labels.txt', 'r')
Lines = file1.readlines()
all_possible_list = []
for line in Lines:
    txt = line.strip().split(":")[1:][0]
    x = re.findall("'(.*?)'", txt)
    try:
        labels = x[0].split(",")
    except:
        x = re.findall('"(.*?)"', txt)
        labels = x[0].split(",")
    labels =[label.strip() for label in labels]
    all_possible_list.append(labels)

topology_dict = {}
imagenet_set = set(imagenet)
correction_dict = {}

for i, row in enumerate(df.iterrows()):
    label_list = row[1].dropna().values
    for label in range(1, len(label_list)):
        new_label = label_list[label].replace("_", " ")
        topology_dict[new_label] = label_list[0]

for i in range(len(all_possible_list)):
    for label in all_possible_list[i]:
        if label in imagenet_set:
            correction_dict[label] = all_possible_list[i]
not_in = []
for label in imagenet:
    if label not in topology_dict.keys():
        not_in.append(label)

for not_in_label in not_in:
    try:
        possible_list = correction_dict[not_in_label]
        for label in possible_list:
            if label in topology_dict.keys():
                new_key = str(not_in_label)
                old_key = str(label)
                coarse_label = topology_dict[old_key]
                topology_dict[new_key] = topology_dict[old_key]
                del topology_dict[old_key]
                break
    except:
        continue

not_in_set = set(not_in)
keys = []
for key in topology_dict.keys():
    if key.title() in not_in_set:
        keys.append(key)
for key in keys:
    dictionary_replace(key.title(), key)

topology_dict["newt"] = topology_dict["eft"]
del topology_dict["eft"]
topology_dict["smooth newt"] = topology_dict["common newt"]
del topology_dict["common newt"]
topology_dict["American dipper"] = topology_dict["water ouzel"]
del topology_dict['water ouzel'] 
topology_dict["fire salamander"] = topology_dict['European fire salamander']
del topology_dict['European fire salamander']
topology_dict["American bullfrog"] = topology_dict['bullfrog']
del topology_dict['bullfrog']
topology_dict["loggerhead sea turtle"] = topology_dict['loggerhead']
del topology_dict['loggerhead']
topology_dict["leatherback sea turtle"] = topology_dict['leatherback turtle']
del topology_dict['leatherback turtle']
topology_dict["green iguana"] = topology_dict['common iguana']
del topology_dict['common iguana']
topology_dict["Carolina anole"] = topology_dict['American chameleon']
del topology_dict['American chameleon']
topology_dict["chameleon"] = topology_dict["African chameleon"]
del topology_dict["African chameleon"]
topology_dict["desert grassland whiptail lizard"] = topology_dict["whiptail"]
del topology_dict["whiptail"]
topology_dict["frilled-necked lizard"] = topology_dict["frilled lizard"]
del topology_dict["frilled lizard"]
topology_dict["European green lizard"] = topology_dict["green lizard"]
del topology_dict["green lizard"]
topology_dict["eastern hog-nosed snake"] = topology_dict["hognose snake"]
del topology_dict["hognose snake"]
topology_dict["smooth green snake"] = topology_dict["green snake"]
del topology_dict["green snake"]
topology_dict["African rock python"] = topology_dict["rock python"]
del topology_dict["rock python"]
topology_dict["Saharan horned viper"] = topology_dict["horned viper"]
del topology_dict["horned viper"]
topology_dict["eastern diamondback rattlesnake"] = topology_dict["diamondback"]
del topology_dict["diamondback"]
topology_dict["yellow garden spider"] = topology_dict["black and gold garden spider"]
del topology_dict["black and gold garden spider"]
topology_dict["European garden spider"] = topology_dict["garden spider"]
del topology_dict["garden spider"]
topology_dict["southern black widow"] = topology_dict["black widow"]
del topology_dict["black widow"]
topology_dict["grey parrot"] = topology_dict["African grey"]
del topology_dict["African grey"]
topology_dict["duck"] = topology_dict["drake"]
del topology_dict["drake"]
topology_dict["red king crab"] = topology_dict["king crab"]
del topology_dict["king crab"]
topology_dict["great egret"] = topology_dict["American egret"]
del topology_dict["American egret"]
topology_dict["common gallinule"] = topology_dict["European gallinule"]
del topology_dict["European gallinule"]
topology_dict["common redshank"] = topology_dict["redshank"]
del topology_dict["redshank"]
topology_dict["Japanese Chin"] = topology_dict["Japanese spaniel"]
del topology_dict["Japanese spaniel"]
topology_dict["Shih Tzu"] = topology_dict["Shih-Tzu"]
del topology_dict["Shih-Tzu"]
topology_dict["King Charles Spaniel"] = topology_dict["Blenheim spaniel"]
del topology_dict["Blenheim spaniel"]
topology_dict["Basset Hound"] = topology_dict["basset"]
del topology_dict["basset"]
topology_dict["Bluetick Coonhound"] = topology_dict["bluetick"]
del topology_dict["bluetick"]
topology_dict["Black and Tan Coonhound"] = topology_dict["black-and-tan coonhound"]
del topology_dict["black-and-tan coonhound"]
topology_dict["Redbone Coonhound"] = topology_dict["redbone"]
del topology_dict["redbone"]
topology_dict["Treeing Walker Coonhound"] = topology_dict["Walker hound"]
del topology_dict["Walker hound"]
topology_dict["Staffordshire Bull Terrier"] = topology_dict["Staffordshire bullterrier"]
del topology_dict["Staffordshire bullterrier"]
topology_dict["Wire Fox Terrier"] = topology_dict["wire-haired fox terrier"]
del topology_dict["wire-haired fox terrier"]
topology_dict["Airedale Terrier"] = topology_dict["Airedale"]
del topology_dict["Airedale"]
topology_dict["Cairn Terrier"] = topology_dict["cairn"]
del topology_dict["cairn"]
topology_dict["Dandie Dinmont Terrier"] = topology_dict["Dandie Dinmont"]
del topology_dict["Dandie Dinmont"]
topology_dict["Boston Terrier"] = topology_dict["Boston bull"]
del topology_dict["Boston bull"]
topology_dict["Scottish Terrier"] = topology_dict["Scotch terrier"]
del topology_dict["Scotch terrier"]
topology_dict["Australian Silky Terrier"] = topology_dict["silky terrier"]
del topology_dict["silky terrier"]
topology_dict["Soft-coated Wheaten Terrier"] = topology_dict["soft-coated wheaten terrier"]
del topology_dict["soft-coated wheaten terrier"]
topology_dict["Lhasa Apso"] = topology_dict["Lhasa"]
del topology_dict["Lhasa"]
topology_dict["Curly-coated Retriever"] = topology_dict["curly-coated retriever"]
del topology_dict["curly-coated retriever"]
topology_dict["German Shorthaired Pointer"] = topology_dict["German short-haired pointer"]
del topology_dict["German short-haired pointer"]
topology_dict["Brittany"] = topology_dict["Brittany spaniel"]
del topology_dict["Brittany spaniel"]
topology_dict["Clumber Spaniel"] = topology_dict["clumber"]
del topology_dict["clumber"]
topology_dict["English Springer Spaniel"] = topology_dict["English springer"]
del topology_dict["English springer"]
topology_dict["Cocker Spaniels"] = topology_dict["cocker spaniel"]
del topology_dict["cocker spaniel"]
topology_dict["Australian Kelpie"] = topology_dict["kelpie"]
del topology_dict["kelpie"]
topology_dict["German Shepherd Dog"] = topology_dict["German shepherd"]
del topology_dict["German shepherd"]
topology_dict["Dobermann"] = topology_dict["Doberman"]
del topology_dict["Doberman"]
topology_dict["Appenzeller Sennenhund"] = topology_dict["Appenzeller"]
del topology_dict["Appenzeller"]
topology_dict["Entlebucher Sennenhund"] = topology_dict["EntleBucher"]
del topology_dict["EntleBucher"]
topology_dict["Bullmastiff"] = topology_dict["bull mastiff"]
del topology_dict["bull mastiff"]
topology_dict["St. Bernard"] = topology_dict["Saint Bernard"]
del topology_dict["Saint Bernard"]
topology_dict["Alaskan Malamute"] = topology_dict["malamute"]
del topology_dict["malamute"]
topology_dict["Leonberger"] = topology_dict["Leonberg"]
del topology_dict["Leonberg"]
topology_dict["Pyrenean Mountain Dog"] = topology_dict["Great Pyrenees"]
del topology_dict["Great Pyrenees"]
topology_dict["Chow Chow"] = topology_dict["chow"]
del topology_dict["chow"]
topology_dict["Griffon Bruxellois"] = topology_dict["Brabancon griffon"]
del topology_dict["Brabancon griffon"]
topology_dict["Pembroke Welsh Corgi"] = topology_dict["Pembroke"]
del topology_dict["Pembroke"]
topology_dict["Cardigan Welsh Corgi"] = topology_dict["Cardigan"]
del topology_dict["Cardigan"]
topology_dict["Mexican hairless dog"] = topology_dict["Mexican hairless"]
del topology_dict["Mexican hairless"]
topology_dict["African wild dog"] = 'wild dog' #topology_dict["African hunting dog"]
del topology_dict["African hunting dog"]
topology_dict["Egyptian Mau"] = topology_dict["Egyptian cat"]
del topology_dict["Egyptian cat"]
topology_dict["Alaskan tundra wolf"] = topology_dict["white wolf"]
del topology_dict["white wolf"]
topology_dict["longhorn beetle"] = topology_dict["long-horned beetle"]
del topology_dict["long-horned beetle"]
topology_dict["red admiral"] = topology_dict["admiral"]
del topology_dict["admiral"]
topology_dict["small white"] = topology_dict["cabbage butterfly"]
del topology_dict["cabbage butterfly"]
topology_dict["gossamer-winged butterfly"] = topology_dict["lycaenid"]
del topology_dict["lycaenid"]
topology_dict["common sorrel"] = topology_dict["sorrel"]
del topology_dict["sorrel"]
topology_dict["Alpine ibex"] = topology_dict["ibex"]
del topology_dict["ibex"]
topology_dict["European polecat"] = topology_dict["polecat"]
del topology_dict["polecat"]
topology_dict["patas monkey"] = topology_dict["patas"]
del topology_dict["patas"]
topology_dict["black-and-white colobus"] = topology_dict["colobus"]
del topology_dict["colobus"]
topology_dict["white-headed capuchin"] = topology_dict["capuchin"]
del topology_dict["capuchin"]
topology_dict["Geoffroy's spider monkey"] = topology_dict["spider monkey"]
del topology_dict["spider monkey"]
topology_dict["common squirrel monkey"] = topology_dict["squirrel monkey"]
del topology_dict["squirrel monkey"]
topology_dict["Asian elephant"] = topology_dict["Indian elephant"]
del topology_dict["Indian elephant"]
topology_dict["African bush elephant"] = topology_dict["African elephant"]
del topology_dict["African elephant"]
topology_dict["clownfish"] = topology_dict["anemone fish"]
del topology_dict["anemone fish"]
topology_dict["waste container"] = "container"
del topology_dict["ashcan"]
topology_dict["Band-Aid"] = topology_dict["Band Aid"]
del topology_dict["Band Aid"]
topology_dict["baluster"] = topology_dict["bannister"]
del topology_dict["bannister"]
topology_dict["military cap"] = topology_dict["bearskin"]
del topology_dict["bearskin"]
topology_dict["bell-cot"] = topology_dict["bell cote"]
del topology_dict["bell cote"]
topology_dict["ring binder"] = topology_dict["binder"]
del topology_dict["binder"]
topology_dict["bottle cap"] = topology_dict["bottlecap"]
del topology_dict["bottlecap"]
topology_dict["high-speed train"] = topology_dict["bullet train"]
del topology_dict["bullet train"]
topology_dict["chain-link fence"] = topology_dict["chainlink fence"]
del topology_dict["chainlink fence"]
topology_dict["clogs"] = topology_dict["clog"]
del topology_dict["clog"]
topology_dict["coffeemaker"] = topology_dict["coffeepot"]
del topology_dict["coffeepot"]
topology_dict["confectionery store"] = topology_dict["confectionery"]
del topology_dict["confectionery"]
topology_dict["crane (machine)"] = topology_dict["crane"]
del topology_dict["crane"]
topology_dict["infant bed"] = topology_dict["crib"]
del topology_dict["crib"]
topology_dict["rotary dial telephone"] = topology_dict["dial telephone"]
del topology_dict["dial telephone"]
topology_dict["drilling rig"] = topology_dict["drilling platform"]
del topology_dict["drilling platform"]
topology_dict["espresso machine"] = topology_dict["espresso maker"]
del topology_dict["espresso maker"]
topology_dict["fire screen sheet"] = topology_dict["fire screen"]
del topology_dict["fire screen"]
topology_dict["four-poster bed"] = topology_dict["four-poster"]
del topology_dict["four-poster"]
topology_dict["gas mask"] = topology_dict["gasmask"]
del topology_dict["gasmask"]
topology_dict["barrette"] = topology_dict["hair slide"]
del topology_dict["hair slide"]
topology_dict["half-track"] = topology_dict["half track"]
del topology_dict["half track"]
topology_dict["hard disk drive"] = topology_dict["hard disc"]
del topology_dict["hard disc"]
topology_dict["hoop skirt"] = topology_dict["hoopskirt"]
del topology_dict["hoopskirt"]
topology_dict["horse-drawn vehicle"] = topology_dict["horse cart"]
del topology_dict["horse cart"]
topology_dict["clothes iron"] = topology_dict["iron"]
del topology_dict["iron"]
topology_dict["jeans"] = topology_dict["jean"]
del topology_dict["jean"]
topology_dict["pulled rickshaw"] = topology_dict["jinrikisha"]
del topology_dict["jinrikisha"]
topology_dict["slip-on shoe"] = topology_dict["Loafer"]
del topology_dict["Loafer"]
topology_dict["mail bag"] = topology_dict["mailbag"]
del topology_dict["mailbag"]
topology_dict["tights"] = "clothing" #### seems like maillot got changed to tank suit and tank suit is a duplicate
topology_dict["match"] = topology_dict["matchstick"]
del topology_dict["matchstick"]
topology_dict["square academic cap"] = topology_dict["mortarboard"]
del topology_dict["mortarboard"]
topology_dict["tent"] = topology_dict["mountain tent"]
del topology_dict["mountain tent"]
topology_dict["bullock cart"] = topology_dict["oxcart"]
del topology_dict["oxcart"]
topology_dict["pajamas"] = topology_dict["pajama"]
del topology_dict["pajama"]
topology_dict["pan flute"] = topology_dict["panpipe"]
del topology_dict["panpipe"]
topology_dict["payphone"] = topology_dict["pay-phone"]
del topology_dict["pay-phone"]
topology_dict["hand plane"] = topology_dict["plane"]
del topology_dict["plane"]
topology_dict["eraser"] = topology_dict["rubber eraser"]
del topology_dict["rubber eraser"]
topology_dict["weighing scale"] = topology_dict["scale"]
del topology_dict["scale"]
topology_dict["slot machine"] = topology_dict["slot"]
del topology_dict["slot"]
topology_dict["solar thermal collector"] = topology_dict["solar dish"]
del topology_dict["solar dish"]
topology_dict["motorboat"] = topology_dict["speedboat"]
del topology_dict["speedboat"]
topology_dict["through arch bridge"] = topology_dict["steel arch bridge"]
del topology_dict["steel arch bridge"]
topology_dict["couch"] = topology_dict["studio couch"]
del topology_dict["studio couch"]
topology_dict["swimsuit"] = topology_dict["swimming trunks"]
del topology_dict["swimming trunks"]
topology_dict["front curtain"] = topology_dict["theater curtain"]
del topology_dict["theater curtain"]
topology_dict["toy store"] = topology_dict["toyshop"]
del topology_dict["toyshop"]
topology_dict["semi-trailer truck"] = topology_dict["trailer truck"]
del topology_dict["trailer truck"]
topology_dict["military aircraft"] = topology_dict["warplane"]
del topology_dict["warplane"]
topology_dict["sink"] = topology_dict["washbasin"]
del topology_dict["washbasin"]
topology_dict["split-rail fence"] = topology_dict["worm fence"]
del topology_dict["worm fence"]
topology_dict["shipwreck"] = topology_dict["wreck"]
del topology_dict["wreck"]
topology_dict["traffic sign"] = topology_dict["street sign"]
del topology_dict["street sign"]
topology_dict["ice pop"] = topology_dict["ice lolly"]
del topology_dict["ice lolly"]
topology_dict["baguette"] = topology_dict["French loaf"]
del topology_dict["French loaf"]
topology_dict["cabbage"] = topology_dict["head cabbage"]
del topology_dict["head cabbage"]
topology_dict["pot pie"] = topology_dict["potpie"]
del topology_dict["potpie"]
topology_dict["shoal"] = topology_dict["sandbar"]
del topology_dict["sandbar"]
topology_dict["horse chestnut seed"] = topology_dict["buckeye"]
del topology_dict["buckeye"]
topology_dict["stinkhorn mushroom"] = topology_dict["stinkhorn"]
del topology_dict["stinkhorn"]
topology_dict["earth star"] = topology_dict["earthstar"]
del topology_dict["earthstar"]
topology_dict["scarf"] = topology_dict["stole"]
del topology_dict["stole"]
topology_dict["oxygen mask"] = "accessory"
topology_dict["Maltese"] = "dog"
topology_dict["Pekingese"] = "dog"

# Save
np.save('coarse_label_mappings.npy', topology_dict) 
